android:
  auto_connect_remote: false
  mirror:
    bit_rate: 4000000
    h264_chunk_size: 32768
    max_fps: 30
    max_size: 0
    video_codec: h264
  refresh_interval: 5
  tasks:
    enabled: []
server:
  ip: 127.0.0.1
  port: 8000
tools:
  macos:
    adb_root_dir: ''
    scrcpy_root_dir: ''
  windows:
    adb_root_dir: C:\Users\czc\Downloads\scrcpy-win64-v3.3.3
    scrcpy_root_dir: C:\Users\czc\Downloads\scrcpy-win64-v3.3.3
